In [2]:
import pandas as pd

l1 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.5/L1_r5_t0.5_net_entrez", sep="\t", names = ["Reg", "Weight"], header=0)
l2 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.5/L2_r5_t0.5_net_entrez", sep="\t", names = ["Reg", "Weight"], header=0)
l3 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.5/L3_r5_t0.5_net_entrez", sep="\t", names = ["Reg", "Weight"],  header=0)
l4 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.5/L4_r5_t0.5_net_entrez", sep="\t", names = ["Reg", "Weight"],  header=0)
l5 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.5/L5_r5_t0.5_net_entrez", sep="\t", names = ["Reg", "Weight"], header=0)

In [3]:
# make a condolidated df with all dataframes and a source column
#add source column to each dataframe
def add_source_column(df, source_name):
    df = df.copy()
    df['Module'] = source_name
    return df

# List of dataframes with their names
dfs_with_names = [
    (l1, 'L1'), (l2, 'L2'), (l3, 'L3'), (l4, 'L4'), (l5, 'L5')
]
#consolidate all dataframes into one and add source
df_list = [add_source_column(df, name) for df, name in dfs_with_names]
consolidated_df = pd.concat(df_list, ignore_index=True)

consolidated_df.head()

                     Reg    Weight Module
0        MT-RNR1_MT-RNR2  0.810587     L1
1  lncRNA-rRPPH1_MT-RNR1 -1.000000     L1
2           RMRP_MT-RNR1 -0.649812     L1
3        MT-RNR1_MT-RNR2  0.876088     L2
4  SNORD56_lncRNA-rRPPH1  0.518775     L2

In [4]:
# Split the 'Reg' column into 'Regulator' and 'TargetGene'
consolidated_df[['Regulator', 'TargetGene']] = consolidated_df['Reg'].str.split('_', expand=True)
consolidated_df.head()

                     Reg    Weight Module      Regulator     TargetGene
0        MT-RNR1_MT-RNR2  0.810587     L1        MT-RNR1        MT-RNR2
1  lncRNA-rRPPH1_MT-RNR1 -1.000000     L1  lncRNA-rRPPH1        MT-RNR1
2           RMRP_MT-RNR1 -0.649812     L1           RMRP        MT-RNR1
3        MT-RNR1_MT-RNR2  0.876088     L2        MT-RNR1        MT-RNR2
4  SNORD56_lncRNA-rRPPH1  0.518775     L2        SNORD56  lncRNA-rRPPH1

In [5]:
consolidated_df.to_csv("HS_consolidated_r5_t0.5.csv", index=False)

# R5T0.25

In [6]:

l1 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.25/L1_r5_t0.25_net_entrez", sep="\t", names = ["Reg", "Weight"], header=0)
l2 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.25/L2_r5_t0.25_net_entrez", sep="\t", names = ["Reg", "Weight"], header=0)
l3 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.25/L3_r5_t0.25_net_entrez", sep="\t", names = ["Reg", "Weight"],  header=0)
l4 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.25/L4_r5_t0.25_net_entrez", sep="\t", names = ["Reg", "Weight"],  header=0)
l5 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.25/L5_r5_t0.25_net_entrez", sep="\t", names = ["Reg", "Weight"], header=0)

In [7]:
# List of dataframes with their names
dfs_with_names = [
    (l1, 'L1'), (l2, 'L2'), (l3, 'L3'), (l4, 'L4'), (l5, 'L5')
]
#consolidate all dataframes into one and add source
df_list = [add_source_column(df, name) for df, name in dfs_with_names]
consolidated_df = pd.concat(df_list, ignore_index=True)

consolidated_df.head()

                     Reg    Weight Module
0  MT-RNR2_lncRNA-rRPPH1  0.255029     L1
1        MT-RNR1_MT-RNR2  0.810587     L1
2          MT-RNR1_RPPH1  0.286754     L1
3  lncRNA-rRPPH1_MT-RNR1 -1.000000     L1
4   lncRNA-rRPPH1_RN7SL1  0.392436     L1

In [8]:
# Split the 'Reg' column into 'Regulator' and 'TargetGene'
consolidated_df[['Regulator', 'TargetGene']] = consolidated_df['Reg'].str.split('_', expand=True)
consolidated_df.head()

                     Reg    Weight Module      Regulator     TargetGene
0  MT-RNR2_lncRNA-rRPPH1  0.255029     L1        MT-RNR2  lncRNA-rRPPH1
1        MT-RNR1_MT-RNR2  0.810587     L1        MT-RNR1        MT-RNR2
2          MT-RNR1_RPPH1  0.286754     L1        MT-RNR1          RPPH1
3  lncRNA-rRPPH1_MT-RNR1 -1.000000     L1  lncRNA-rRPPH1        MT-RNR1
4   lncRNA-rRPPH1_RN7SL1  0.392436     L1  lncRNA-rRPPH1         RN7SL1

In [9]:
consolidated_df.to_csv("HS_consolidated_r5_t0.25.csv", index=False)

# r5t0.125

In [10]:
l1 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.125/L1_r5_t0.125_net_entrez", sep="\t", names = ["Reg", "Weight"], header=0)
l2 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.125/L2_r5_t0.125_net_entrez", sep="\t", names = ["Reg", "Weight"], header=0)
l3 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.125/L3_r5_t0.125_net_entrez", sep="\t", names = ["Reg", "Weight"],  header=0)
l4 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.125/L4_r5_t0.125_net_entrez", sep="\t", names = ["Reg", "Weight"],  header=0)
l5 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.125/L5_r5_t0.125_net_entrez", sep="\t", names = ["Reg", "Weight"], header=0)

In [11]:
# List of dataframes with their names
dfs_with_names = [
    (l1, 'L1'), (l2, 'L2'), (l3, 'L3'), (l4, 'L4'), (l5, 'L5')
]
#consolidate all dataframes into one and add source
df_list = [add_source_column(df, name) for df, name in dfs_with_names]
consolidated_df = pd.concat(df_list, ignore_index=True)

consolidated_df.head()

                     Reg    Weight Module
0          ERBB2_MT-RNR1  0.150434     L1
1         RNU5A-1_RN7SL1  0.125395     L1
2  MT-RNR2_lncRNA-rRPPH1  0.255029     L1
3        MT-RNR1_RARRES1  0.154415     L1
4        MT-RNR1_MT-RNR2  0.810587     L1

In [12]:
# Split the 'Reg' column into 'Regulator' and 'TargetGene'
consolidated_df[['Regulator', 'TargetGene']] = consolidated_df['Reg'].str.split('_', expand=True)
consolidated_df.head()

                     Reg    Weight Module Regulator     TargetGene
0          ERBB2_MT-RNR1  0.150434     L1     ERBB2        MT-RNR1
1         RNU5A-1_RN7SL1  0.125395     L1   RNU5A-1         RN7SL1
2  MT-RNR2_lncRNA-rRPPH1  0.255029     L1   MT-RNR2  lncRNA-rRPPH1
3        MT-RNR1_RARRES1  0.154415     L1   MT-RNR1        RARRES1
4        MT-RNR1_MT-RNR2  0.810587     L1   MT-RNR1        MT-RNR2

In [13]:
consolidated_df.to_csv("HS_consolidated_r5_t0.125.csv", index=False)

# R5T0.0625

In [14]:
l1 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.0625/L1_r5_t0.0625_net_entrez", sep="\t", names = ["Reg", "Weight"], header=0)
l2 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.0625/L2_r5_t0.0625_net_entrez", sep="\t", names = ["Reg", "Weight"], header=0)
l3 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.0625/L3_r5_t0.0625_net_entrez", sep="\t", names = ["Reg", "Weight"],  header=0)
l4 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.0625/L4_r5_t0.0625_net_entrez", sep="\t", names = ["Reg", "Weight"],  header=0)
l5 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.0625/L5_r5_t0.0625_net_entrez", sep="\t", names = ["Reg", "Weight"], header=0)

In [15]:
# List of dataframes with their names
dfs_with_names = [
    (l1, 'L1'), (l2, 'L2'), (l3, 'L3'), (l4, 'L4'), (l5, 'L5')
]
#consolidate all dataframes into one and add source
df_list = [add_source_column(df, name) for df, name in dfs_with_names]
consolidated_df = pd.concat(df_list, ignore_index=True)

# Split the 'Reg' column into 'Regulator' and 'TargetGene'
consolidated_df[['Regulator', 'TargetGene']] = consolidated_df['Reg'].str.split('_', expand=True)
consolidated_df.head()

                     Reg    Weight Module Regulator     TargetGene
0           RPL23_RN7SL1  0.080442     L1     RPL23         RN7SL1
1          ERBB2_MT-RNR1  0.150434     L1     ERBB2        MT-RNR1
2         RNU5A-1_RN7SL1  0.125395     L1   RNU5A-1         RN7SL1
3  MT-RNR2_lncRNA-rRPPH1  0.255029     L1   MT-RNR2  lncRNA-rRPPH1
4        MT-RNR1_RARRES1  0.154415     L1   MT-RNR1        RARRES1

In [16]:
consolidated_df.to_csv("HS_consolidated_r5_t0.0625.csv", index=False)

# R5T0.015625

In [17]:
l1 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.015625/L1_r5_t0.015625_net_entrez", sep="\t", names = ["Reg", "Weight"], header=0)
l2 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.015625/L2_r5_t0.015625_net_entrez", sep="\t", names = ["Reg", "Weight"], header=0)
l3 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.015625/L3_r5_t0.015625_net_entrez", sep="\t", names = ["Reg", "Weight"],  header=0)
l4 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.015625/L4_r5_t0.015625_net_entrez", sep="\t", names = ["Reg", "Weight"],  header=0)
l5 = pd.read_csv("/Users/irmaskaljo/codedev/thesis/Data/GRN/Human_coronavirus/R5T0.015625/L5_r5_t0.015625_net_entrez", sep="\t", names = ["Reg", "Weight"], header=0)

In [18]:
# List of dataframes with their names
dfs_with_names = [
    (l1, 'L1'), (l2, 'L2'), (l3, 'L3'), (l4, 'L4'), (l5, 'L5')
]
#consolidate all dataframes into one and add source
df_list = [add_source_column(df, name) for df, name in dfs_with_names]
consolidated_df = pd.concat(df_list, ignore_index=True)

# Split the 'Reg' column into 'Regulator' and 'TargetGene'
consolidated_df[['Regulator', 'TargetGene']] = consolidated_df['Reg'].str.split('_', expand=True)
consolidated_df.head()

               Reg    Weight Module Regulator TargetGene
0     RPL23_RN7SL1  0.080442     L1     RPL23     RN7SL1
1    ERBB2_MT-RNR1  0.150434     L1     ERBB2    MT-RNR1
2   RNU5A-1_RN7SL1  0.125395     L1   RNU5A-1     RN7SL1
3  SNORD102_RN7SL1  0.042558     L1  SNORD102     RN7SL1
4  MT-RNR2_RNU5A-1  0.047711     L1   MT-RNR2    RNU5A-1

In [19]:
consolidated_df.to_csv("HS_consolidated_r5_t0.015625.csv", index=False)