In [3]:
import pandas as pd

g1 = pd.read_csv("/Users/irmaskaljo/codedev/masters_thesis/Data/GRN/Yeast/scr_size_5_r5/G1_r5_t0.1_net", sep="\t", names = ["Reg", "Weight"], header=0)
l1 = pd.read_csv("/Users/irmaskaljo/codedev/masters_thesis/Data/GRN/Yeast/scr_size_5_r5/L1_r5_t0.1_net", sep="\t", names = ["Reg", "Weight"], header=0)
l2 = pd.read_csv("/Users/irmaskaljo/codedev/masters_thesis/Data/GRN/Yeast/scr_size_5_r5/L2_r5_t0.1_net", sep="\t", names = ["Reg", "Weight"], header=0)
l3 = pd.read_csv("/Users/irmaskaljo/codedev/masters_thesis/Data/GRN/Yeast/scr_size_5_r5/L3_r5_t0.1_net", sep="\t", names = ["Reg", "Weight"],  header=0)
l4 = pd.read_csv("/Users/irmaskaljo/codedev/masters_thesis/Data/GRN/Yeast/scr_size_5_r5/L4_r5_t0.1_net", sep="\t", names = ["Reg", "Weight"],  header=0)
l5 = pd.read_csv("/Users/irmaskaljo/codedev/masters_thesis/Data/GRN/Yeast/scr_size_5_r5/L5_r5_t0.1_net", sep="\t", names = ["Reg", "Weight"], header=0)
l6 = pd.read_csv("/Users/irmaskaljo/codedev/masters_thesis/Data/GRN/Yeast/scr_size_5_r5/L6_r5_t0.1_net", sep="\t", names = ["Reg", "Weight"], header=0)
l7 = pd.read_csv("/Users/irmaskaljo/codedev/masters_thesis/Data/GRN/Yeast/scr_size_5_r5/L7_r5_t0.1_net", sep="\t", names = ["Reg", "Weight"], header=0)
l8 = pd.read_csv("/Users/irmaskaljo/codedev/masters_thesis/Data/GRN/Yeast/scr_size_5_r5/L8_r5_t0.1_net", sep="\t", names = ["Reg", "Weight"], header=0)
l9 = pd.read_csv("/Users/irmaskaljo/codedev/masters_thesis/Data/GRN/Yeast/scr_size_5_r5/L9_r5_t0.1_net", sep="\t", names = ["Reg", "Weight"], header=0)
l10 = pd.read_csv("/Users/irmaskaljo/codedev/masters_thesis/Data/GRN/Yeast/scr_size_5_r5/L10_r5_t0.1_net", sep="\t", names = ["Reg", "Weight"], header=0)
l11 = pd.read_csv("/Users/irmaskaljo/codedev/masters_thesis/Data/GRN/Yeast/scr_size_5_r5/L11_r5_t0.1_net", sep="\t", names = ["Reg", "Weight"], header=0)
l12 = pd.read_csv("/Users/irmaskaljo/codedev/masters_thesis/Data/GRN/Yeast/scr_size_5_r5/L12_r5_t0.1_net", sep="\t", names = ["Reg", "Weight"], header=0)

In [4]:
# make a condolidated df with all dataframes and a source column
#add source column to each dataframe
def add_source_column(df, source_name):
    df = df.copy()
    df['Module'] = source_name
    return df

# List of dataframes with their names
dfs_with_names = [
    (g1, 'G1'),
    (l1, 'L1'), (l2, 'L2'), (l3, 'L3'), (l4, 'L4'), (l5, 'L5'),
    (l6, 'L6'), (l7, 'L7'), (l8, 'L8'), (l9, 'L9'), (l10, 'L10'),
    (l11, 'L11'), (l12, 'L12')
]
#consolidate all dataframes into one and add source
df_list = [add_source_column(df, name) for df, name in dfs_with_names]
consolidated_df = pd.concat(df_list, ignore_index=True)

consolidated_df.head()

                 Reg    Weight Module
0  YKL106C-A_YDL232W  0.141283     G1
1    YKL106C-A_snR18  0.122029     G1
2    YKL106C-A_snR39  0.101112     G1
3  YEL032C-A_YDL232W  0.164023     G1
4  YDL232W_YKL106C-A  0.141621     G1

In [5]:
# Split the 'Reg' column into 'Regulator' and 'TargetGene'
consolidated_df[['Regulator', 'TargetGene']] = consolidated_df['Reg'].str.split('_', expand=True)
consolidated_df.head()

                 Reg    Weight Module  Regulator TargetGene
0  YKL106C-A_YDL232W  0.141283     G1  YKL106C-A    YDL232W
1    YKL106C-A_snR18  0.122029     G1  YKL106C-A      snR18
2    YKL106C-A_snR39  0.101112     G1  YKL106C-A      snR39
3  YEL032C-A_YDL232W  0.164023     G1  YEL032C-A    YDL232W
4  YDL232W_YKL106C-A  0.141621     G1    YDL232W  YKL106C-A

In [7]:
consolidated_df.to_csv("Yeast_consolidated_r5_t0.1.csv", index=False)